# ============================================
# WORKFLOW SIMPLE PARA PRODUCCIÓN
# ============================================
# 
# Usa este workflow temporalmente mientras
# arreglamos el smart-pipeline
#
# ============================================

name: Simple Production Deploy

on:
  push:
    branches: [main]

jobs:
  production-deploy:
    uses: carlosorbegoso/workflow-templates/.github/workflows/simple-production.yml@main
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

# ============================================
# ESTE WORKFLOW:
# ============================================
#
# ✅ Solo se ejecuta en push a main
# ✅ Build → Push → Deploy (sin complicaciones)
# ✅ Sin condiciones complejas
# ✅ Flujo lineal y simple
#
# TIEMPO ESTIMADO: 5-8 minutos
#
# ============================================
# PARA USAR:
# ============================================
#
# 1. Reemplaza tu workflow actual con este
# 2. Haz push a main
# 3. Verifica que Build → Push → Deploy funcionen
# 4. Una vez que funcione, volvemos al smart-pipeline
#
# ============================================