services:
  app:
    image: ghcr.io/carlosorbegoso/yape-hub:${APP_VERSION:-main}
    container_name: yape-hub
    ports:
      - "8080:8080"
    env_file:
      - ~/.env  # ← Leer .env de la raíz para compartir entre apps
    environment:
      # Servidor
      - QUARKUS_HTTP_HOST=0.0.0.0
      - QUARKUS_HTTP_PORT=8080
      - QUARKUS_PROFILE=prod

      # Base de datos - PRODUCCIÓN CON SSL
      - QUARKUS_DATASOURCE_USERNAME=${DB_USERNAME}
      - QUARKUS_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - QUARKUS_DATASOURCE_REACTIVE_URL=${DATABASE_URL}
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      - QUARKUS_DATASOURCE_REACTIVE_POSTGRESQL_SSL_MODE=allow

      # JPA/Hibernate - IMPORTANTE
      - QUARKUS_JPA_HIBERNATE_DATABASE_GENERATION=validate
      - QUARKUS_JPA_HIBERNATE_LOG_SQL=false

      # SmallRye JWT - CONFIGURACIÓN CORRECTA
      - SMALLRYE_JWT_SIGN_KEY_SECRET=${JWT_SECRET}
      - MP_JWT_VERIFY_ISSUER=${JWT_ISSUER}

      # CORS
      - QUARKUS_HTTP_CORS_ORIGINS=${CORS_ORIGINS}
      - QUARKUS_HTTP_CORS_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - QUARKUS_HTTP_CORS_HEADERS=accept,authorization,content-type,x-requested-with

      # Email
      - QUARKUS_MAILER_FROM=${MAILER_FROM}
      - QUARKUS_MAILER_HOST=${SMTP_HOST}
      - QUARKUS_MAILER_PORT=${SMTP_PORT:-587}
      - QUARKUS_MAILER_USERNAME=${EMAIL_USERNAME}
      - QUARKUS_MAILER_PASSWORD=${EMAIL_PASSWORD}
      - QUARKUS_MAILER_START_TLS=true

      # Logging - Optimizado para servidor pequeño
      - QUARKUS_LOG_LEVEL=WARN
      - QUARKUS_LOG_CATEGORY_\"org.hibernate.sql\".LEVEL=ERROR

    # Recursos para servidor pequeño (1 CPU)
    deploy:
      resources:
        limits:
          cpus: '0.8'    # 80% de 1 CPU
          memory: 768M   # 768MB máximo
        reservations:
          cpus: '0.1'    # 10% CPU reservado
          memory: 256M   # 256MB reservado

    restart: unless-stopped

    # Healthcheck optimizado para servidor pequeño
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health/ready"]
      interval: 60s      # Menos frecuente
      timeout: 15s       # Más tiempo
      retries: 2         # Menos reintentos
      start_period: 90s  # Más tiempo de inicio

    networks:
      - yape-network

networks:
  yape-network:
    driver: bridge