services:
  app:
    image: ghcr.io/carlosorbegoso/yape-hub:${APP_VERSION:-main}
    container_name: yape-hub
    ports:
      - "8080:8080"
    environment:
      # Servidor
      - QUARKUS_HTTP_HOST=0.0.0.0
      - QUARKUS_HTTP_PORT=8080
      - QUARKUS_PROFILE=prod

      # Base de datos - PRODUCCIÓN CON SSL
      - QUARKUS_DATASOURCE_USERNAME=${DB_USERNAME}
      - QUARKUS_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - QUARKUS_DATASOURCE_REACTIVE_URL=${DATABASE_URL}
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      - QUARKUS_DATASOURCE_REACTIVE_POSTGRESQL_SSL_MODE=require

      # JPA/Hibernate - IMPORTANTE
      - QUARKUS_JPA_HIBERNATE_DATABASE_GENERATION=validate
      - QUARKUS_JPA_HIBERNATE_LOG_SQL=false

      # SmallRye JWT - CONFIGURACIÓN CORRECTA
      - SMALLRYE_JWT_SIGN_KEY_SECRET=${JWT_SECRET}
      - MP_JWT_VERIFY_ISSUER=${JWT_ISSUER}

      # CORS
      - QUARKUS_HTTP_CORS_ORIGINS=${CORS_ORIGINS}
      - QUARKUS_HTTP_CORS_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - QUARKUS_HTTP_CORS_HEADERS=accept,authorization,content-type,x-requested-with

      # Email
      - QUARKUS_MAILER_FROM=${MAILER_FROM}
      - QUARKUS_MAILER_HOST=${SMTP_HOST}
      - QUARKUS_MAILER_PORT=${SMTP_PORT:-587}
      - QUARKUS_MAILER_USERNAME=${EMAIL_USERNAME}
      - QUARKUS_MAILER_PASSWORD=${EMAIL_PASSWORD}
      - QUARKUS_MAILER_START_TLS=true

      # Logging - Completo para servidor potente
      - QUARKUS_LOG_LEVEL=INFO
      - QUARKUS_LOG_CATEGORY_\"org.hibernate.sql\".LEVEL=WARN

    # Recursos para servidor potente (4+ CPUs)
    deploy:
      resources:
        limits:
          cpus: '3'      # 3 CPUs máximo
          memory: 4G     # 4GB máximo
        reservations:
          cpus: '1'      # 1 CPU reservado
          memory: 1G     # 1GB reservado

    restart: unless-stopped

    # Healthcheck optimizado para servidor potente
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health/ready"]
      interval: 20s      # Más frecuente
      timeout: 5s        # Más rápido
      retries: 5         # Más reintentos
      start_period: 45s  # Menos tiempo de inicio

    networks:
      - yape-network

networks:
  yape-network:
    driver: bridge