name: Production Deploy (Fast)

on:
  workflow_call:
    inputs:
      java_version:
        description: 'Java version to use'
        required: false
        default: '21'
        type: string
      use_ghcr:
        description: 'Use GitHub Container Registry'
        required: false
        default: true
        type: boolean
      push_to_registry:
        description: 'Push image to registry'
        required: false
        default: true
        type: boolean
        
    secrets:
      # Deployment secrets
      SSH_HOST:
        required: true
      SSH_USER:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      DEPLOY_PATH:
        required: true
      
      # Registry secrets
      GHCR_USERNAME:
        required: false
      GHCR_PAT:
        required: false
      
      # Database secrets
      DB_USERNAME:
        required: false
      DB_PASSWORD:
        required: false

jobs:
  # Solo Build -> Push -> Deploy (rápido para producción)
  build:
    name: Build Native Image
    uses: carlosorbegoso/workflow-templates/.github/workflows/build.yml@main

  push:
    name: Push to Registry
    needs: build
    uses: carlosorbegoso/workflow-templates/.github/workflows/push.yml@main
    with:
      use_ghcr: ${{ inputs.use_ghcr }}
      push_to_registry: ${{ inputs.push_to_registry }}
    secrets:
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_PAT: ${{ secrets.GHCR_PAT }}

  deploy:
    name: Deploy to Production
    needs: push
    uses: carlosorbegoso/workflow-templates/.github/workflows/deploy.yml@main
    with:
      image_version: ${{ needs.push.outputs.image-version }}
      push_to_registry: ${{ inputs.push_to_registry }}
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}