name: Build JVM Image

on:
  workflow_call:
    outputs:
      artifact-name:
        description: 'Generated artifact name'
        value: ${{ jobs.build.outputs.artifact-name }}

jobs:
  build:
    name: Build JVM
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      artifact-name: ${{ steps.artifact.outputs.name }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gradle/caches
          key: ${{ runner.os }}-jvm-${{ hashFiles('**/pom.xml', '**/build.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-jvm-

      - name: Detect build tool
        id: build-tool
        run: |
          if [ -f "pom.xml" ]; then
            echo "tool=maven" >> $GITHUB_OUTPUT
          elif [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
            echo "tool=gradle" >> $GITHUB_OUTPUT
          else
            echo "ERROR: No build tool found"
            exit 1
          fi

      - name: Build with Maven (JVM)
        if: steps.build-tool.outputs.tool == 'maven'
        run: |
          ./mvnw clean package -DskipTests

      - name: Build with Gradle (JVM)
        if: steps.build-tool.outputs.tool == 'gradle'
        run: |
          ./gradlew clean build -x test --no-daemon

      - name: Prepare JVM artifact
        id: artifact
        run: |
          mkdir -p build-output
          find . -maxdepth 3 -name '*.jar' -type f -exec cp -v {} build-output/ \;
          
          PROJECT_NAME=$(basename ${{ github.repository }})
          ARTIFACT_NAME="${PROJECT_NAME}-jvm-jars"
          echo "name=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT
          
          echo "JARs prepared:"
          ls -la build-output/

      - name: Upload JVM JARs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact.outputs.name }}
          path: build-output/
          retention-days: 1