name: Push to Docker Hub

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  push:
    runs-on: ubuntu-latest
    outputs:
      docker-image: ${{ steps.docker-image.outputs.full-image }}
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4

      - name: Validate Dockerfile
        run: |
          if [ ! -f "src/main/docker/Dockerfile.native" ]; then
            echo "Error: Dockerfile.native no encontrado"
            exit 1
          fi

      - name: Extract Docker image name
        id: docker-image
        run: |
          PROJECT_NAME=$(basename ${{ github.repository }})
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/${PROJECT_NAME}"
          echo "image-name=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "full-image=docker.io/$IMAGE_NAME:latest" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/${{ steps.docker-image.outputs.image-name }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/main/docker/Dockerfile.native
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Docker image info
        run: |
          echo "Imagen: ${{ steps.docker-image.outputs.full-image }}"
          echo "Hub: https://hub.docker.com/r/${{ steps.docker-image.outputs.image-name }}"